### ISSUE TITLE
Breaking change in version 0.28.0

### ISSUE THREAD

**Issue by EndBug** [vercel/ncc#693]
Hi, I've found out that when I use version ^0.28.0 my GitHub action, which uses ncc to compile, is no longer able to require a file provided by GitHub.

Here is the code (TypeScript) that I'm using:
```ts
const eventPath = process.env.GITHUB_EVENT_PATH ?? '/github/workflow/event.json',
    event = eventPath && require(eventPath)
```

`GITHUB_EVENT_PATH` is an env variable provided by GitHub, and in my case its value is `/home/runner/work/_temp/_github_workflow/event.json`
`require(eventPath)` throws this error:
> Error: Cannot find module '/home/runner/work/_temp/_github_workflow/event.json'

I've verified that the file still exists and is still valid JSON, and that when I compile my current code with version 0.27.0 it runs with no issues.

**Comment by guybedford** [comment]
@EndBug can you perhaps look at the generated code to see the difference between what is being output here? It's difficult to look into this without a full replication.

**Comment by EndBug** [comment]
@guybedford Sure!
These are the two build files (I've turned off compression for now, since that would make it unreadable)
- 0.27.0: https://github.com/EndBug/add-and-commit/blob/682e840606b6548b292626282c96ddc1049d4d5f/lib/index.js#L11115
- 0.28.0: https://github.com/EndBug/add-and-commit/blob/6d00245624492ed4e9efa4c0df829668e1ae00ef/lib/index.js#L10912

Here is the part of compiled code that corresponds to the interested region:

```js
// 0.27.0, line 11115
const eventPath = process.env.GITHUB_EVENT_PATH, event = eventPath && require(eventPath) // ...

// 0.28.0, line 10912
const eventPath = process.env.GITHUB_EVENT_PATH, event = eventPath && __nccwpck_require__(875)(eventPath) // ...
```

Looking at these it seems like the `require` has been turned to some kind of webpack require, is that correct?

**Comment by Songkeys** [comment]
Seems that it gets transpiled into a webpackEmptyContext: https://github.com/EndBug/add-and-commit/blob/6d00245624492ed4e9efa4c0df829668e1ae00ef/lib/index.js#L11066-L11077

Originally, `require(var)` won't be recognised by ncc since it might be a "unable-to-be-resolved" dynamic require, but the new webpack introduced in 0.28.0 looks like transforming it directly at compile time rather than leaving it there...?

I think you could change it into a more complex form to not make it recognisable as a temporary solution for now, like:

```javascript
const myRequire = (id) => require(id);
// ...
const eventPath = process.env.GITHUB_EVENT_PATH ?? '/github/workflow/event.json',
    event = eventPath && myRequire(eventPath) // I think this won't be transpiled and you can use your file path at runtime
```

**Comment by EndBug** [comment]
I've tried using different functions (anonymous, declared as constants, as functions, with generic arguments, ...) but webpack seems to be smarter 😅

**Comment by WtfJoke** [comment]
Not sure, but it sounds like it could be a duplicate (or the same cause) of https://github.com/vercel/ncc/issues/686 (which is fixed in 0.28.3).
Does it work with 0.28.3?

**Comment by EndBug** [comment]
Nope, same issue

Compiled code: 

https://github.com/EndBug/add-and-commit/blob/724766a764093e5f3967a7ed7fa8528620504696/lib/index.js#L11048
```js
const eventPath = process.env.GITHUB_EVENT_PATH, event = eventPath && __nccwpck_require__(875)(eventPath)
````

https://github.com/EndBug/add-and-commit/blob/724766a764093e5f3967a7ed7fa8528620504696/lib/index.js#L6860-L6873
```js
/***/ 875:
/***/ ((module) => {

function webpackEmptyContext(req) {
	var e = new Error("Cannot find module '" + req + "'");
	e.code = 'MODULE_NOT_FOUND';
	throw e;
}
webpackEmptyContext.keys = () => ([]);
webpackEmptyContext.resolve = webpackEmptyContext;
webpackEmptyContext.id = 875;
module.exports = webpackEmptyContext;

/***/ }),
```

**Comment by guybedford** [comment]
I just tried to create a replication of this case with the following test file:

test.js
```js
const eventPath = process.env.GITHUB_EVENT_PATH, event = eventPath && require(eventPath);
console.log(eventPath);
console.log(event);
```

When I build this with ncc the output definitely retains the `require` and it does not get wrapped into a webpack require.

Can you try and share an exact / minimal replication of the issue?

**Comment by EndBug** [comment]
I've tested your sample and it correctly compiles using `require`. I started tweaking it until I found the thing that breaks this behavior. It's the fact that the variable is declared inside a function: when I declare it in a function (synchronous or asynchronous) it gets compiled to `__nccwpck_require__(875)`, but when in the global scope or in a block like an `if` statement it correctly compiles to `require`

**Comment by guybedford** [comment]
@EndBug I just tried building:

test.js
```js
function test () {
  const eventPath = process.env.GITHUB_EVENT_PATH, event = eventPath && require(eventPath);
  console.log(eventPath);
  console.log(event);
}
test();
```

but that also still works correctly for me as well. Please let me know the exact steps here.

**Comment by EndBug** [comment]
Sorry, I've checked again and it seems to happen only with ___exported___ functions and variables.

<details>
<summary>Works correctly when compiling functions that are not exported</summary>

```ts
/// test.ts
async function test() {
  const eventPath = process.env.GITHUB_EVENT_PATH,
    eventL = eventPath && require(eventPath)

  console.log(eventPath)
  console.log(eventL)
}
test()
```
```js
// index.js
// ...
function test() {
    return __awaiter(this, void 0, void 0, function* () {
        const eventPath = process.env.GITHUB_EVENT_PATH, eventL = eventPath && require(eventPath);
        console.log(eventPath);
        console.log(eventL);
    });
}
test();
// ...
```
</details>

<details>
<summary>Compiles incorrectly when using exported functions</summary>

```ts
// test.ts
export async function test() {
  const eventPath = process.env.GITHUB_EVENT_PATH,
    eventL = eventPath && require(eventPath)

  console.log(eventPath)
  console.log(eventL)
}
test()
```

```js
// index.js
// ...
function test() {
    return __awaiter(this, void 0, void 0, function* () {
        const eventPath = process.env.GITHUB_EVENT_PATH, eventL = eventPath && __nccwpck_require__(875)(eventPath);
        console.log(eventPath);
        console.log(eventL);
    });
}
test();
// ...
```
</details>

The same thing happens with variables:

<details>
<summary>Non-exported variable</summary>

```ts
// test.ts
const eventPath = process.env.GITHUB_EVENT_PATH,
  eventL = eventPath && require(eventPath)

console.log(eventPath)
console.log(eventL)
```

```js
// index.js
/******/ (() => { // webpackBootstrap
/******/ 	"use strict";
/******/ 	/* webpack/runtime/compat */
/******/ 	
/******/ 	if (typeof __nccwpck_require__ !== 'undefined') __nccwpck_require__.ab = __dirname + "/";/************************************************************************/
var __webpack_exports__ = {};

const eventPath = process.env.GITHUB_EVENT_PATH, eventL = eventPath && require(eventPath);
console.log(eventPath);
console.log(eventL);

module.exports = __webpack_exports__;
/******/ })()
;
```
</details>

<details>
<summary>Exported variable</summary>

```ts
// test.ts
export const eventPath = process.env.GITHUB_EVENT_PATH,
  eventL = eventPath && require(eventPath)

console.log(eventPath)
console.log(eventL)
```

```js
// index.js
// ...
const eventPath = process.env.GITHUB_EVENT_PATH, eventL = eventPath && __nccwpck_require__(875)(eventPath);
console.log(eventPath);
console.log(eventL);
// ...
```
</details>

**Comment by guybedford** [comment]
@EndBug you should not be using `require` and `export` in the same source. Rather, you should pick one or the other module format. There are no guarantees on behaviours when mixing.
