### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by dinkoivanov** [vercel/ncc#649]
Hi,

I hit a problem after migrating from ncc 0.23.0 to 0.27.0. I'm using node 14.15.2.

To reproduce:

1. Create an app.js file with the following content:
```
const fs = require('fs');
let settingsPath = './settings.json';
if (fs.existsSync(settingsPath)) {
    let settings = require(settingsPath);
    console.log(settings);
}
```
2. Create a settings.json file with content: `{}`.
3. Execute: `ncc build app.js -o .`
4. Run the packaged application using `node index.js. This will result in the following error:
```
Error: Cannot find module './settings.json'
    at webpackEmptyContext (C:\projects\auroramm\sample123\index.js:21:10)
    at Object.498 (C:\projects\auroramm\sample123\index.js:11:44)
    at __nccwpck_require__ (C:\projects\auroramm\sample123\index.js:61:42)
    at C:\projects\auroramm\sample123\index.js:83:18
    at Object.<anonymous> (C:\projects\auroramm\sample123\index.js:84:12)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m
}
```
Note that extracting the `fs.existsSync()` call in a separate variable produces proper result.

**Comment by zhu956645239** [comment]
How did you solve it?

**Comment by gokaybiz** [comment]
Error: Cannot find module 'node:http'
